import './globals.css'
import { Providers } from './providers/provider'
import ThemeSwitcher from './components/ThemeSwitcher';
import { SocketProvider } from './providers/SocketProvider';
export const metadata = {
  title: 'Vista',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <header className='py-6'>
              <nav className='container flex items-center justify-between'>
                <ThemeSwitcher />
              </nav>
          </header>
          <SocketProvider> 
            {children}
          </SocketProvider>
        </Providers>
      </body>
    </html>
  )
}
